spring:
  profiles.active: "local"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com"
  data:
    mongodb:
      uri: "mongodb+srv://spring-boot:B4OTfcEisNGHBebQ@cluster0.zztf6.mongodb.net/?retryWrites=true&w=majority"
      database: "nutrisearch"
      auto-index-creation: true