spring:
  profiles.active: "local"
  data:
    mongodb:
      uri: "mongodb+srv://spring-boot:B4OTfcEisNGHBebQ@cluster0.zztf6.mongodb.net/?retryWrites=true&w=majority"
      database: "nutrisearch"
      auto-index-creation: true